# Header
nav:
  Archives: /archives
  # Categories: /category
  Tags: /tag
  About: /about

# fancybox
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# hexo-renderer-pandoc
pandoc:
  args:
    - '-f'
    - 'markdown'
    - '-t'
    - 'html'
    - '--mathjax'
